version: '3.0'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AwesomePass_1234
    restart: on-failure
  schoolmanagementapp:
    depends_on:
      - db
    build: 
      context: .
    image: brheat/schoolmanagementapp:runtime
    ports:
      - "8080:5000"
      - "8081:5001"
    environment:
      - ASPNETCORE_KESTREL__Certificates__Default__Password=awesomepass
      - ASPNETCORE_KESTREL__Certificates__Default__Path=/https/schoolmanagementapp.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/